create database Digital_Habits;
use Digital_Habits;
create table responses(
id int auto_increment primary key,
user_type enum('Student','Teacher','Any Other') not null,
full_name varchar(100),
age int,
gender enum('Male','Female','Others'),
college_name varchar(255),
year_of_study enum('1st','2nd','3rd','Other'),
field_of_study varchar(100),
preferred_device enum('Mobile','Laptop','Tablet','Other'),
daily_screen_time enum('Less than 1 hour','1-2 hours','3-4 hours','More than 4 hours'),
social_media_platforms enum('Instagram','BGMI','Whatsapp','YouTube','Snapchat','FreeFire','Twitter','LinkedIn'),
during_lectures enum('Yes','No'),
primary_purpose enum('Entertainment','Education','Networking','News','Shopping','Just for scrolling'),
check_frequency enum('Every few minutes','Hourly','Few times a day','Rarely'),
academic_impact enum('Yes','No'),
social_media_detox enum('Yes','No'),
favourite_content enum('Memes & entertainment','News & current affairs','Educational content','Fashion & lifestyle','Gaming & technology'),
follow_influencers enum('Yes','No'),
influencer_name varchar(255),
purchase_based_on_ADs enum('Yes','No'),
mental_health_impact enum('Yes','No','Maybe'),
privacy_concern enum('Yes','No'),
cyberbullying_experience enum('Yes','No'),
security_measures enum('Yes','No'),
prefer_online_communication enum('Yes','No'),
reduce_usage_for_productivity int,
sleep_impact enum('Yes','No'),
deleted_account enum('Yes','No'),
additional_comments text,
submission_time timestamp default current_timestamp
);